import type { AdminGift } from "@/lib/admin-store";

type GiftCategory = {
  category: string;
  items: string[];
};

export const giftCatalog: GiftCategory[] = [
  {
    category: "Perfumes, Fragrâncias e Cuidados Pessoais",
    items: [
      "Perfumes com fragrâncias florais ou frutadas",
      "Body splash",
      "Hidratante corporal",
      "Óleo corporal",
      "Sabonete líquido",
      "Kits de banho",
      "Esfoliante corporal",
      "Gel de limpeza facial",
      "Água micelar",
      "Demaquilante",
      "Hidratante facial",
      "Protetor labial",
      "Máscaras faciais",
      "Produtos para cuidados com a pele",
      "Kits de skincare",
      "Necessaire para produtos de beleza",
    ],
  },
  {
    category: "Maquiagem e Beleza",
    items: [
      "Gloss",
      "Batom",
      "Blush",
      "Iluminador",
      "Máscara para cílios",
      "Delineador",
      "Lápis para olhos",
      "Paleta de sombras",
      "Corretivo",
      "Pó facial",
      "Esponjas de maquiagem",
      "Pincéis de maquiagem",
      "Maleta ou organizador de maquiagem",
      "Espelho de mesa com iluminação",
      "Escova de cabelo",
      "Secador ou modelador de cabelo",
    ],
  },
  {
    category: "Joias, Semijoias e Acessórios",
    items: [
      "Colares em tons dourados",
      "Pulseiras em tons dourados",
      "Brincos em tons dourados",
      "Anéis em tons dourados",
      "Pingentes",
      "Tornozeleiras",
      "Relógios",
      "Porta-joias",
      "Presilhas de cabelo",
      "Tiaras",
      "Óculos de sol",
      "Cintos",
      "Carteiras",
    ],
  },
  {
    category: "Bolsas e Organização",
    items: [
      "Bolsas de passeio",
      "Bolsas pequenas para festas",
      "Bolsas transversais",
      "Mochilas",
      "Mini mochilas",
      "Necessaires",
      "Organizadores de bolsa",
      "Estojos",
      "Porta-cartões",
      "Carteiras",
      "Malas ou bolsas para viagens curtas",
    ],
  },
  {
    category: "Calçados",
    items: [
      "Tênis casual tamanho 36",
      "Tênis esportivo tamanho 36",
      "Sandálias tamanho 36",
      "Rasteirinhas tamanho 36",
      "Sapatilhas tamanho 36",
      "Chinelo tamanho 36",
      "Pantufas tamanho 36",
      "Botas tamanho 36",
      "Sapatos casuais tamanho 36",
    ],
  },
  {
    category: "Roupas",
    items: [
      "Calças jeans tamanho M ou 38",
      "Calças sociais tamanho M ou 38",
      "Shorts tamanho M ou 38",
      "Saias tamanho M ou 38",
      "Camisas tamanho M ou 38",
      "Blusas tamanho M ou 38",
      "Croppeds tamanho M ou 38",
      "Vestidos casuais tamanho M ou 38",
      "Vestidos para passeio tamanho M ou 38",
      "Pijamas tamanho M ou 38",
      "Roupas de academia tamanho M ou 38",
      "Conjuntos tamanho M ou 38",
      "Jaquetas tamanho M ou 38",
      "Moletons tamanho M ou 38",
      "Cardigãs tamanho M ou 38",
    ],
  },
  {
    category: "Tecnologia e Acessórios Eletrônicos",
    items: [
      "Fones de ouvido",
      "Headset",
      "Caixinha de som Bluetooth",
      "Suporte para celular",
      "Tripé para celular",
      "Ring light",
      "Carregador portátil",
      "Capinhas para celular",
      "Organizador de cabos",
      "Luminária para mesa de estudos",
      "Relógio digital",
      "Smartwatch ou pulseira inteligente",
    ],
  },
  {
    category: "Estudos, Criatividade e Papelaria",
    items: [
      "Caderno inteligente",
      "Planner",
      "Agenda",
      "Diário",
      "Cadernos personalizados",
      "Canetas coloridas",
      "Marca-textos",
      "Kits de papelaria",
      "Estojos",
      "Livros",
      "Marcadores de páginas",
      "Organizadores de mesa",
      "Porta-lápis",
      "Luminária para leitura",
      "Quadro de planejamento",
    ],
  },
  {
    category: "Decoração e Itens para o Quarto",
    items: [
      "Porta-retratos",
      "Luminárias decorativas",
      "Fitas ou luzes de LED",
      "Espelho de mesa",
      "Espelho decorativo",
      "Almofadas",
      "Mantas",
      "Caixa organizadora",
      "Porta-joias",
      "Difusor de aromas",
      "Velas aromáticas",
      "Relógio de mesa",
      "Quadros decorativos",
      "Letreiros luminosos",
      "Organizadores para maquiagem",
      "Organizadores de bijuterias",
    ],
  },
  {
    category: "Itens para o Dia a Dia",
    items: [
      "Garrafinhas de água",
      "Copos térmicos",
      "Canecas",
      "Squeezes",
      "Nécessaires",
      "Bolsinhas organizadoras",
      "Porta-óculos",
      "Guarda-chuva compacto",
      "Kit de viagem",
      "Almofada de pescoço",
      "Organizadores para mochila ou bolsa",
    ],
  },
  {
    category: "Música, Filmes e Entretenimento",
    items: [
      "Fones de ouvido",
      "Caixinha de som",
      "Livros",
      "Jogos de tabuleiro",
      "Quebra-cabeças",
      "Cartões-presente",
      "Assinaturas de plataformas digitais",
      "Ingressos para cinema",
      "Vale-presente de lojas que ela goste",
    ],
  },
  {
    category: "Uma Lembrança Especial Escolhida com Carinho",
    items: [
      "Álbum de fotografias",
      "Caixa de recordações",
      "Luminária",
      "Espelho",
      "Almofada personalizada",
      "Diário",
      "Caderno inteligente",
      "Livro especial",
      "Caneca personalizada",
      "Quadro decorativo",
      "Caixa de música",
      "Pingente simbólico",
      "Carta acompanhada de uma lembrança",
      "Kit personalizado montado com carinho",
    ],
  },
  {
    category: "Experiências e Presentes Diferentes",
    items: [
      "Vale-presente",
      "Dia de beleza",
      "Sessão de fotos",
      "Ingressos para cinema",
      "Ingressos para shows ou eventos",
      "Passeios",
      "Cursos",
      "Oficinas de maquiagem",
      "Cursos de fotografia",
      "Experiências gastronômicas",
      "Contribuição para uma viagem",
      "Contribuição para um sonho especial",
    ],
  },
];

export const defaultGiftSuggestions: AdminGift[] = giftCatalog.flatMap((group) =>
  group.items.map((name, index) => ({
    id: `default-${group.category.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${index}`,
    category: group.category,
    name,
    description: "",
    imageUrl: "",
    linkUrl: "",
    size: "",
    color: "",
    notes: "",
    priority: "",
    active: true,
  })),
);
